name = 'wormhole/wormhole'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'wormhole/wormhole'"

[repository]
user = 'wormhole'
project = 'wormhole'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
